#!/usr/bin/env bash
[[ -L "${BASH_SOURCE[0]}" ]] && REPO="$(cd "$(dirname $(readlink "${BASH_SOURCE[0]}"))/" && pwd -P)" || REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/" && pwd -P)"

# Keep track of the calling directory
PWD=$(pwd)



# Always work from the root of singularity
cd ${REPO}
source "${REPO}/lib/main.sh"
_self="$0"

if [[ $# -eq 0 ]]; then
  echo "Error: no options passed"
  exit 1
fi


if [[ "$@" =~ "--help" ]]; then
  _Help::Help "${@}"
  exit
elif [[ "$@" =~ "--fzf" ]]; then
  # Generate fzf history list
  _Help::Fzf "${@}"
  exit
fi

if [[ $(type -t "${1}") == "function" ]]; then
  func=$(_Help::Input_count "${1}")
  OLDIFS=$IFS; IFS=':' read -a count <<< "${func}"; IFS=${OLDIFS}
  if [[ "${count[0]}" == "${#}" ]] || [[ "${count[1]}" == "${#}" ]] || [[ "${count[2]}" == "99" ]] && [[ "${#}" -ge "${count[0]}" ]]; then
    _History::Add "${@}"
    eval "${@}"
  else
    _Help::Autohelp "${1}"
  fi
else
  if type fzf &>/dev/null; then
    if [[ $(${_self} ${1} --fzf &>/dev/null; echo $?) == 0 ]]; then
      option=$(${_self} ${1} --fzf | fzf --no-preview --no-sort -1)
      func=$(_Help::Input_count "${option}")
      OLDIFS=$IFS; IFS=':' read -a count <<< "${func}"; IFS=${OLDIFS}
      if [[ "${count[0]}" == "${#}" ]] || [[ "${count[1]}" == "${#}" ]] || [[ "${count[2]}" == "99" ]] && [[ "${#}" -ge "${count[0]}" ]]; then 
        _History::Add "${option}" "${@:2}"
        eval "${option}" "${@:2}"
      else
        _Help::Autohelp "${option}"
      fi
    else
      _Log::Die 1 "Unknown Command"
    fi
  else
    _Log::Die 1 "Unknown Command"
  fi
fi